baseurl = "/"
languageCode = "en-uk"
title = "GentleR Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    
[[menu.main]]
    name = "Meeting times"
    url = "/times/"
    
[[menu.main]]
    name = "Contacts"
    url = "/contacts/"
    
[[menu.main]]
    name = "Slack"
    url = "https://join.slack.com/t/gentler/shared_invite/enQtNTU0MzM3NjQwNTAwLTViZWQxZjhkYWY1YWFiZGYwZjdjOWNlZWQ0N2NjYTlkOWE1MGRjODMwZWRjMDg5NWFmMTJkZjY5MWJkYWQ4NzE"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

